### ISSUE TITLE
NO_DATA + UNKNOWN

### ISSUE THREAD

**Issue by benedikt-haug** [Apoullo/CEPGP_NoOfficerNote#1]
Dear developer,
when trying to use the addon, I get an error called NO_DATA + UNKNOWN:
![grafik](https://user-images.githubusercontent.com/2534537/118050144-0de10000-b37f-11eb-8122-d8aa0071a601.png)

Could you help me figure this out?

Thanks a bunch :)

**Comment by benedikt-haug** [comment]
Ah, I get the description now. I need to import standings with the format like that:

Arthur | 2 | 4
Fred | 3 | 5
Arnie | 4 | 6

which is achieved by just copy pasting google rows.

Thank you for developing this.

**Comment by Apoullo** [comment]
Glad to hear that you figure this out.
My English is not well, so the description is bad. haha.
I already quit the WOW after I conquerd NAXX.
So the addon maybe need some fixed.
